#############################################################################
# Generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#  Jul 21, 2022 04:09:29 PM CST  platform: Darwin
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #edf0f3
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #edf0f3
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 280x300+2233+270
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3648 1089
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "pyGUS"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "root" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command mode1 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Mode 1} 
    vTcl:DefineAlias "$top.but51" "Button1" vTcl:WidgetProc "root" 1
    bind $top.but51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Single target in each image}
    }
    vTcl:copy_lock $top.but51
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command mode2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Mode 2} 
    vTcl:DefineAlias "$top.but52" "Button1_1" vTcl:WidgetProc "root" 1
    bind $top.but52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Target and positive reference in each image}
    }
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command mode3 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Mode 3} 
    vTcl:DefineAlias "$top.but53" "Button1_1_1" vTcl:WidgetProc "root" 1
    bind $top.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Target and color checker in each image}
    }
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command mode4 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Mode 4} 
    vTcl:DefineAlias "$top.but54" "Button1_1_1_1" vTcl:WidgetProc "root" 1
    bind $top.but54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Manually select}
    }
    button $top.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command checker -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Color checker} 
    vTcl:DefineAlias "$top.but55" "Button2" vTcl:WidgetProc "root" 1
    bind $top.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Macbeth color checker for print}
    }
    button $top.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command help -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Help 
    vTcl:DefineAlias "$top.but56" "Button3" vTcl:WidgetProc "root" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but51 \
        -in $top -x 0 -relx 0.321 -y 0 -rely 0.1 -width 100 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.321 -y 0 -rely 0.25 -width 100 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.321 -y 0 -rely 0.4 -width 100 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.321 -y 0 -rely 0.55 -width 100 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.107 -y 0 -rely 0.75 -width 100 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.536 -y 0 -rely 0.75 -width 100 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 500x280+2597+46
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3648 1089
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Mode 1"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "root_1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "root_1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Negative reference image} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "root_1" 1
    entry $site_3_0.ent48 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable ref1 -width 212 
    vTcl:DefineAlias "$site_3_0.ent48" "Entry1" vTcl:WidgetProc "root_1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1" vTcl:WidgetProc "root_1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.351 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra50 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra50" "Frame1_1" vTcl:WidgetProc "root_1" 1
    set site_3_0 $top.fra50
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Positive reference image} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1_1" vTcl:WidgetProc "root_1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1_2" vTcl:WidgetProc "root_1" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable ref2 -width 212 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1_1" vTcl:WidgetProc "root_1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.351 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra47" "Frame1_1_1" vTcl:WidgetProc "root_1" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Target images} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1_1_1" vTcl:WidgetProc "root_1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1_2_1" vTcl:WidgetProc "root_1" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable targets -width 212 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1_1_1" vTcl:WidgetProc "root_1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.158 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.197 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    checkbutton $top.che48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -selectcolor #edf0f3 \
        -text {Automatic adjust white balance} -variable che48 
    vTcl:DefineAlias "$top.che48" "Checkbutton1" vTcl:WidgetProc "root_1" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command run_mode1 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Run 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "root_1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.071 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.286 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.5 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.che48 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.75 -width 0 -relwidth 0.44 \
        -height 0 -relheight 0.079 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.58 -y 0 -rely 0.732 -width 107 -relwidth 0 \
        -height 38 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top3 {base} {
    global vTcl
    if {$base == ""} {
        set base .top3
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 500x200+2630+378
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3648 1089
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Mode 2"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "root_1_1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra46" "Frame1_2" vTcl:WidgetProc "root_1_1" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Reference image} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "root_1_1" 1
    bind $site_3_0.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Left negative, right positive}
    }
    entry $site_3_0.ent48 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable ref1 -width 212 
    vTcl:DefineAlias "$site_3_0.ent48" "Entry1" vTcl:WidgetProc "root_1_1" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1" vTcl:WidgetProc "root_1_1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.132 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.241 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra47" "Frame1_1_1_1" vTcl:WidgetProc "root_1_1" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Target images} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1_1_1" vTcl:WidgetProc "root_1_1" 1
    bind $site_3_0.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Left target, right positive reference}
    }
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1_2_1" vTcl:WidgetProc "root_1_1" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable targets -width 212 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1_1_1" vTcl:WidgetProc "root_1_1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.154 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.197 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command run_mode2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Run 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "root_1_1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.07 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.4 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.2 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.38 -y 0 -rely 0.7 -width 100 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top4 {base} {
    global vTcl
    if {$base == ""} {
        set base .top4
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 500x280+2639+622
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3648 1089
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Mode 3"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "root_1_2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra46" "Frame1_3" vTcl:WidgetProc "root_1_2" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Negative reference image} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "root_1_2" 1
    bind $site_3_0.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Left negative reference, right color checker}
    }
    entry $site_3_0.ent48 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable ref1 -width 212 
    vTcl:DefineAlias "$site_3_0.ent48" "Entry1" vTcl:WidgetProc "root_1_2" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1" vTcl:WidgetProc "root_1_2" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.351 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra50 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra50" "Frame1_1_2" vTcl:WidgetProc "root_1_2" 1
    set site_3_0 $top.fra50
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Positive reference image} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1_1" vTcl:WidgetProc "root_1_2" 1
    bind $site_3_0.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Left positive reference, right color checker}
    }
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1_2" vTcl:WidgetProc "root_1_2" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable ref2 -width 212 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1_1" vTcl:WidgetProc "root_1_2" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.351 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra47" "Frame1_1_1_2" vTcl:WidgetProc "root_1_2" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Target images} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1_1_1" vTcl:WidgetProc "root_1_2" 1
    bind $site_3_0.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Left target, right color checker}
    }
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1_2_1" vTcl:WidgetProc "root_1_2" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable targets -width 212 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1_1_1" vTcl:WidgetProc "root_1_2" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.158 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.197 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command run_mode3 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Run 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "root_1_2" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.071 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.fra50 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.286 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.5 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.143 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.38 -y 0 -rely 0.75 -width 107 -relwidth 0 \
        -height 38 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top5 {base} {
    global vTcl
    if {$base == ""} {
        set base .top5
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightbackground #d9d9d9 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 500x120+2138+702
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3648 1089
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Mode 4"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "root_1_1_1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightbackground #d9d9d9 -highlightcolor black \
        -width 255 
    vTcl:DefineAlias "$top.fra47" "Frame1_1_1_1_1" vTcl:WidgetProc "root_1_1_1" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 \
        -activeforeground systemPressedButtonTextColor -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #d9d9d9 \
        -highlightcolor black -text {Target images} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1_1_1" vTcl:WidgetProc "root_1_1_1" 1
    bind $site_3_0.lab47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Left target, right positive reference}
    }
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_file -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Open 
    vTcl:DefineAlias "$site_3_0.but49" "Button1_2_1" vTcl:WidgetProc "root_1_1_1" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #d9d9d9 -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -textvariable targets -width 212 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry1_1_1" vTcl:WidgetProc "root_1_1_1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.154 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.197 -height 0 -relheight 0.55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.833 -y 0 -rely 0.125 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 0 -relx 0.395 -y 0 -rely 0.125 -width 200 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command run_mode2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Run 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "root_1_1_1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.167 -width 0 -relwidth 0.912 \
        -height 0 -relheight 0.333 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.583 -width 100 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top3 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}
set btop4 ""
if {$vTcl(borrow)} {
    set btop4 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop4 $vTcl(tops)] != -1} {
        set btop4 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop4
Window show .top4 $btop4
if {$vTcl(borrow)} {
    $btop4 configure -background plum
}
set btop5 ""
if {$vTcl(borrow)} {
    set btop5 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop5 $vTcl(tops)] != -1} {
        set btop5 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop5
Window show .top5 $btop5
if {$vTcl(borrow)} {
    $btop5 configure -background plum
}

