#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jul 26, 2022 04:34:12 PM CST  platform: Darwin

import sys
import tkinter as tk
from tkinter import messagebox, filedialog, scrolledtext

import ui

def open_file(title, entry, single=True):
    def func():
        if single:
            a = filedialog.askopenfilename(title=title)
        else:
            a = filedialog.askopenfilenames(title=title)
        entry.delete(0, 'end')
        entry.insert(0, a)
    return func


def checker():
    pass


def help():
    pass


def run_mode1():
    global _top2, _w2
    _top2 = tk.Toplevel(root)
    _w2 = ui.root_mode1(_top2)

def run_mode2():
    # Creates a toplevel widget.
    global _top3, _w3
    _top3 = tk.Toplevel(root)
    _w3 = ui.root_mode2(_top3)


def run_mode3():
    # Creates a toplevel widget.
    global _top4, _w4
    _top4 = tk.Toplevel(root)
    _w4 = ui.root_mode3(_top4)


def run_mode4():
    global _top5, _w5
    _top5 = tk.Toplevel(root)
    _w5 = ui.root_1_1_1(_top5)


def run():
    # call core
    pass


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = ui.Root(_top1)
    root.mainloop()


if __name__ == '__main__':
    ui.start_up()
